# SPDX-FileCopyrightText: Axle Duggan (axlecoffee) <contact@axle.coffee>
# SPDX-License-Identifier: CC0-1.0

version = 1

SPDX-PackageName = "Mocha"
SPDX-PackageSupplier = "Axle Duggan (axlecoffee) <contact@axle.coffee>"
SPDX-PackageDownloadLocation = "https://github.com/catboyaddons/mocha"

[[annotations]]
path = ["**/*.kt", "**/*.java"]
SPDX-License-Identifier = "LGPL-3.0-only"
SPDX-FileCopyrightText = "Axle Duggan (axlecoffee) <contact@axle.coffee>"

[[annotations]]
path = [
    "**/*.gradle.kts",
    "**/gradle.properties",
    "**/gradle-wrapper.properties",
    "**/libs.versions.toml",
    "**/fabric.mod.json",
    "**/*.mixins.json",
    "**/mixins.*.json",
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "Axle (axle.coffee) <contact@axle.coffee>"

[[annotations]]
path = [
    "gradlew",
    "gradlew.bat",
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "Axle (axle.coffee) <contact@axle.coffee>"

[[annotations]]
path = "LICENSES/**"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "Axle (axle.coffee) <contact@axle.coffee>"
