name: Publish

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set Maven URL
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "MAVEN_URL=https://maven.axle.coffee/releases" >> $GITHUB_ENV
          else
            echo "MAVEN_URL=https://maven.axle.coffee/snapshots" >> $GITHUB_ENV
          fi

      - name: Publish all versions to Maven
        run: |
          chmod +x ./gradlew
          ./gradlew publishAllMaven --stacktrace
        env:
          MAVEN_URL: ${{ env.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
